# Generated by Django 5.2.2 on 2025-06-20 19:37

import backend.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_shop_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', backend.models.UserManager()),
            ],
        ),
    ]
