# Generated by Django 5.2.2 on 2025-06-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Список заказов'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ('-name',), 'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-name',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ('-name',), 'verbose_name': 'Магазин', 'verbose_name_plural': 'Список магазинов'},
        ),
        migrations.AddConstraint(
            model_name='productinfo',
            constraint=models.UniqueConstraint(fields=('product', 'shop', 'ext_id'), name='unique_product_info'),
        ),
    ]
