# Generated by Django 5.2.2 on 2025-06-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationtoken',
            options={'verbose_name': 'Токен верификации почты', 'verbose_name_plural': 'Токены верификации почты'},
        ),
        migrations.AlterModelOptions(
            name='productparameter',
            options={'verbose_name': 'Параметр продукта', 'verbose_name_plural': 'Параметры продукта'},
        ),
    ]
